services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=FinanceTrackerDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
      - Jwt__Key=${JWT_KEY}
    restart: on-failure:5

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"